---

- hosts: all
  become: true
  tasks: 

  - name: update repo cache and upgrade distribution
    tags: always
    apt:
        upgrade: dist
        update_cache: yes
    changed_when: false    
    when: ansible_distribution in ["Kali GNU/Linux"]

- hosts: all
  become: true
  roles:
      - base
      - workstations


